apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config
  namespace: ns-dev
data:
  GMAIL_USER: "domain.gmail.com"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ns-dev
data:
  NEXT_PUBLIC_BACKEND_URL: "http://localhost:5000"
