apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-hmg
  namespace: ns-hmg
spec:
  hard:
    pods: "10"
    requests.cpu: "6"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limits-hmg
  namespace: ns-hmg
spec:
  limits:
    - default:
        cpu: "300m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "100Mi"
      type: Container
