[api_server]
vm_api ansible_host=localhost

[db_server]
vm_postgres ansible_host=localhost

[api_server:vars]
ansible_port=2222
ansible_user=root
ansible_password=root
ansible_ssh_extra_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

[db_server:vars]
ansible_port=2223
ansible_user=root
ansible_password=root
ansible_ssh_extra_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null