[gateway_server]
127.0.0.1

[gateway_server:vars]
ansible_port=2300
ansible_user=root
ansible_ssh_private_key_file=../terraform/floci-api.pem
ansible_ssh_extra_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

[backend_server]
127.0.0.1

[backend_server:vars]
ansible_port=2301
ansible_user=root
ansible_ssh_private_key_file=../terraform/backend.pem
ansible_ssh_extra_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null