apiVersion: v1
kind: Secret
metadata:
  name: auth-api-secret
  namespace: ns-dev
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-0.postgres-headless:5432/postgres"
  JWT_SECRET: "changeme-jwt-secret-strong-random-value"
  GMAIL_APP_PASSWORD: "changeme-gmail-app-password"
