name: owasp zap

on:
  workflow_dispatch:
    inputs:
      target_url:
        required: false
        default: "http://localhost:5000"

jobs:
  zap-scan:
    runs-on: self-hosted
    steps:
      - name: run zap
        run: |
          zap.sh -cmd -quickurl ${{ github.event.inputs.target_url }} -quickout report.html -I

      - name: upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: report.html
